//go:build windows

package keymap

type VirtualKeyCode uint16

// 来源 https://learn.microsoft.com/en-us/windows/win32/inputdev/virtual-key-codes
const (
	VK_LBUTTON                         VirtualKeyCode = 0x01
	VK_RBUTTON                         VirtualKeyCode = 0x02
	VK_CANCEL                          VirtualKeyCode = 0x03
	VK_MBUTTON                         VirtualKeyCode = 0x04
	VK_XBUTTON1                        VirtualKeyCode = 0x05
	VK_XBUTTON2                        VirtualKeyCode = 0x06
	VK_BACK                            VirtualKeyCode = 0x08
	VK_TAB                             VirtualKeyCode = 0x09
	VK_CLEAR                           VirtualKeyCode = 0x0C
	VK_RETURN                          VirtualKeyCode = 0x0D
	VK_SHIFT                           VirtualKeyCode = 0x10
	VK_CONTROL                         VirtualKeyCode = 0x11
	VK_MENU                            VirtualKeyCode = 0x12
	VK_PAUSE                           VirtualKeyCode = 0x13
	VK_CAPITAL                         VirtualKeyCode = 0x14
	VK_KANA                            VirtualKeyCode = 0x15
	VK_HANGUL                          VirtualKeyCode = 0x15
	VK_IME_ON                          VirtualKeyCode = 0x16
	VK_JUNJA                           VirtualKeyCode = 0x17
	VK_FINAL                           VirtualKeyCode = 0x18
	VK_HANJA                           VirtualKeyCode = 0x19
	VK_KANJI                           VirtualKeyCode = 0x19
	VK_IME_OFF                         VirtualKeyCode = 0x1A
	VK_ESCAPE                          VirtualKeyCode = 0x1B
	VK_CONVERT                         VirtualKeyCode = 0x1C
	VK_NONCONVERT                      VirtualKeyCode = 0x1D
	VK_ACCEPT                          VirtualKeyCode = 0x1E
	VK_MODECHANGE                      VirtualKeyCode = 0x1F
	VK_SPACE                           VirtualKeyCode = 0x20
	VK_PRIOR                           VirtualKeyCode = 0x21
	VK_NEXT                            VirtualKeyCode = 0x22
	VK_END                             VirtualKeyCode = 0x23
	VK_HOME                            VirtualKeyCode = 0x24
	VK_LEFT                            VirtualKeyCode = 0x25
	VK_UP                              VirtualKeyCode = 0x26
	VK_RIGHT                           VirtualKeyCode = 0x27
	VK_DOWN                            VirtualKeyCode = 0x28
	VK_SELECT                          VirtualKeyCode = 0x29
	VK_PRINT                           VirtualKeyCode = 0x2A
	VK_EXECUTE                         VirtualKeyCode = 0x2B
	VK_SNAPSHOT                        VirtualKeyCode = 0x2C
	VK_INSERT                          VirtualKeyCode = 0x2D
	VK_DELETE                          VirtualKeyCode = 0x2E
	VK_HELP                            VirtualKeyCode = 0x2F
	VK_0                               VirtualKeyCode = 0x30
	VK_1                               VirtualKeyCode = 0x31
	VK_2                               VirtualKeyCode = 0x32
	VK_3                               VirtualKeyCode = 0x33
	VK_4                               VirtualKeyCode = 0x34
	VK_5                               VirtualKeyCode = 0x35
	VK_6                               VirtualKeyCode = 0x36
	VK_7                               VirtualKeyCode = 0x37
	VK_8                               VirtualKeyCode = 0x38
	VK_9                               VirtualKeyCode = 0x39
	VK_A                               VirtualKeyCode = 0x41
	VK_B                               VirtualKeyCode = 0x42
	VK_C                               VirtualKeyCode = 0x43
	VK_D                               VirtualKeyCode = 0x44
	VK_E                               VirtualKeyCode = 0x45
	VK_F                               VirtualKeyCode = 0x46
	VK_G                               VirtualKeyCode = 0x47
	VK_H                               VirtualKeyCode = 0x48
	VK_I                               VirtualKeyCode = 0x49
	VK_J                               VirtualKeyCode = 0x4A
	VK_K                               VirtualKeyCode = 0x4B
	VK_L                               VirtualKeyCode = 0x4C
	VK_M                               VirtualKeyCode = 0x4D
	VK_N                               VirtualKeyCode = 0x4E
	VK_O                               VirtualKeyCode = 0x4F
	VK_P                               VirtualKeyCode = 0x50
	VK_Q                               VirtualKeyCode = 0x51
	VK_R                               VirtualKeyCode = 0x52
	VK_S                               VirtualKeyCode = 0x53
	VK_T                               VirtualKeyCode = 0x54
	VK_U                               VirtualKeyCode = 0x55
	VK_V                               VirtualKeyCode = 0x56
	VK_W                               VirtualKeyCode = 0x57
	VK_X                               VirtualKeyCode = 0x58
	VK_Y                               VirtualKeyCode = 0x59
	VK_Z                               VirtualKeyCode = 0x5A
	VK_LWIN                            VirtualKeyCode = 0x5B
	VK_RWIN                            VirtualKeyCode = 0x5C
	VK_APPS                            VirtualKeyCode = 0x5D
	VK_SLEEP                           VirtualKeyCode = 0x5F
	VK_NUMPAD0                         VirtualKeyCode = 0x60
	VK_NUMPAD1                         VirtualKeyCode = 0x61
	VK_NUMPAD2                         VirtualKeyCode = 0x62
	VK_NUMPAD3                         VirtualKeyCode = 0x63
	VK_NUMPAD4                         VirtualKeyCode = 0x64
	VK_NUMPAD5                         VirtualKeyCode = 0x65
	VK_NUMPAD6                         VirtualKeyCode = 0x66
	VK_NUMPAD7                         VirtualKeyCode = 0x67
	VK_NUMPAD8                         VirtualKeyCode = 0x68
	VK_NUMPAD9                         VirtualKeyCode = 0x69
	VK_MULTIPLY                        VirtualKeyCode = 0x6A
	VK_ADD                             VirtualKeyCode = 0x6B
	VK_SEPARATOR                       VirtualKeyCode = 0x6C
	VK_SUBTRACT                        VirtualKeyCode = 0x6D
	VK_DECIMAL                         VirtualKeyCode = 0x6E
	VK_DIVIDE                          VirtualKeyCode = 0x6F
	VK_F1                              VirtualKeyCode = 0x70
	VK_F2                              VirtualKeyCode = 0x71
	VK_F3                              VirtualKeyCode = 0x72
	VK_F4                              VirtualKeyCode = 0x73
	VK_F5                              VirtualKeyCode = 0x74
	VK_F6                              VirtualKeyCode = 0x75
	VK_F7                              VirtualKeyCode = 0x76
	VK_F8                              VirtualKeyCode = 0x77
	VK_F9                              VirtualKeyCode = 0x78
	VK_F10                             VirtualKeyCode = 0x79
	VK_F11                             VirtualKeyCode = 0x7A
	VK_F12                             VirtualKeyCode = 0x7B
	VK_F13                             VirtualKeyCode = 0x7C
	VK_F14                             VirtualKeyCode = 0x7D
	VK_F15                             VirtualKeyCode = 0x7E
	VK_F16                             VirtualKeyCode = 0x7F
	VK_F17                             VirtualKeyCode = 0x80
	VK_F18                             VirtualKeyCode = 0x81
	VK_F19                             VirtualKeyCode = 0x82
	VK_F20                             VirtualKeyCode = 0x83
	VK_F21                             VirtualKeyCode = 0x84
	VK_F22                             VirtualKeyCode = 0x85
	VK_F23                             VirtualKeyCode = 0x86
	VK_F24                             VirtualKeyCode = 0x87
	VK_NUMLOCK                         VirtualKeyCode = 0x90
	VK_SCROLL                          VirtualKeyCode = 0x91
	VK_LSHIFT                          VirtualKeyCode = 0xA0
	VK_RSHIFT                          VirtualKeyCode = 0xA1
	VK_LCONTROL                        VirtualKeyCode = 0xA2
	VK_RCONTROL                        VirtualKeyCode = 0xA3
	VK_LMENU                           VirtualKeyCode = 0xA4
	VK_RMENU                           VirtualKeyCode = 0xA5
	VK_BROWSER_BACK                    VirtualKeyCode = 0xA6
	VK_BROWSER_FORWARD                 VirtualKeyCode = 0xA7
	VK_BROWSER_REFRESH                 VirtualKeyCode = 0xA8
	VK_BROWSER_STOP                    VirtualKeyCode = 0xA9
	VK_BROWSER_SEARCH                  VirtualKeyCode = 0xAA
	VK_BROWSER_FAVORITES               VirtualKeyCode = 0xAB
	VK_BROWSER_HOME                    VirtualKeyCode = 0xAC
	VK_VOLUME_MUTE                     VirtualKeyCode = 0xAD
	VK_VOLUME_DOWN                     VirtualKeyCode = 0xAE
	VK_VOLUME_UP                       VirtualKeyCode = 0xAF
	VK_MEDIA_NEXT_TRACK                VirtualKeyCode = 0xB0
	VK_MEDIA_PREV_TRACK                VirtualKeyCode = 0xB1
	VK_MEDIA_STOP                      VirtualKeyCode = 0xB2
	VK_MEDIA_PLAY_PAUSE                VirtualKeyCode = 0xB3
	VK_LAUNCH_MAIL                     VirtualKeyCode = 0xB4
	VK_LAUNCH_MEDIA_SELECT             VirtualKeyCode = 0xB5
	VK_LAUNCH_APP1                     VirtualKeyCode = 0xB6
	VK_LAUNCH_APP2                     VirtualKeyCode = 0xB7
	VK_OEM_1                           VirtualKeyCode = 0xBA
	VK_OEM_PLUS                        VirtualKeyCode = 0xBB
	VK_OEM_COMMA                       VirtualKeyCode = 0xBC
	VK_OEM_MINUS                       VirtualKeyCode = 0xBD
	VK_OEM_PERIOD                      VirtualKeyCode = 0xBE
	VK_OEM_2                           VirtualKeyCode = 0xBF
	VK_OEM_3                           VirtualKeyCode = 0xC0
	VK_GAMEPAD_A                       VirtualKeyCode = 0xC3
	VK_GAMEPAD_B                       VirtualKeyCode = 0xC4
	VK_GAMEPAD_X                       VirtualKeyCode = 0xC5
	VK_GAMEPAD_Y                       VirtualKeyCode = 0xC6
	VK_GAMEPAD_RIGHT_SHOULDER          VirtualKeyCode = 0xC7
	VK_GAMEPAD_LEFT_SHOULDER           VirtualKeyCode = 0xC8
	VK_GAMEPAD_LEFT_TRIGGER            VirtualKeyCode = 0xC9
	VK_GAMEPAD_RIGHT_TRIGGER           VirtualKeyCode = 0xCA
	VK_GAMEPAD_DPAD_UP                 VirtualKeyCode = 0xCB
	VK_GAMEPAD_DPAD_DOWN               VirtualKeyCode = 0xCC
	VK_GAMEPAD_DPAD_LEFT               VirtualKeyCode = 0xCD
	VK_GAMEPAD_DPAD_RIGHT              VirtualKeyCode = 0xCE
	VK_GAMEPAD_MENU                    VirtualKeyCode = 0xCF
	VK_GAMEPAD_VIEW                    VirtualKeyCode = 0xD0
	VK_GAMEPAD_LEFT_THUMBSTICK_BUTTON  VirtualKeyCode = 0xD1
	VK_GAMEPAD_RIGHT_THUMBSTICK_BUTTON VirtualKeyCode = 0xD2
	VK_GAMEPAD_LEFT_THUMBSTICK_UP      VirtualKeyCode = 0xD3
	VK_GAMEPAD_LEFT_THUMBSTICK_DOWN    VirtualKeyCode = 0xD4
	VK_GAMEPAD_LEFT_THUMBSTICK_RIGHT   VirtualKeyCode = 0xD5
	VK_GAMEPAD_LEFT_THUMBSTICK_LEFT    VirtualKeyCode = 0xD6
	VK_GAMEPAD_RIGHT_THUMBSTICK_UP     VirtualKeyCode = 0xD7
	VK_GAMEPAD_RIGHT_THUMBSTICK_DOWN   VirtualKeyCode = 0xD8
	VK_GAMEPAD_RIGHT_THUMBSTICK_RIGHT  VirtualKeyCode = 0xD9
	VK_GAMEPAD_RIGHT_THUMBSTICK_LEFT   VirtualKeyCode = 0xDA
	VK_OEM_4                           VirtualKeyCode = 0xDB
	VK_OEM_5                           VirtualKeyCode = 0xDC
	VK_OEM_6                           VirtualKeyCode = 0xDD
	VK_OEM_7                           VirtualKeyCode = 0xDE
	VK_OEM_8                           VirtualKeyCode = 0xDF
	VK_OEM_102                         VirtualKeyCode = 0xE2
	VK_PROCESSKEY                      VirtualKeyCode = 0xE5
	VK_PACKET                          VirtualKeyCode = 0xE7
	VK_ATTN                            VirtualKeyCode = 0xF6
	VK_CRSEL                           VirtualKeyCode = 0xF7
	VK_EXSEL                           VirtualKeyCode = 0xF8
	VK_EREOF                           VirtualKeyCode = 0xF9
	VK_PLAY                            VirtualKeyCode = 0xFA
	VK_ZOOM                            VirtualKeyCode = 0xFB
	VK_NONAME                          VirtualKeyCode = 0xFC
	VK_PA1                             VirtualKeyCode = 0xFD
	VK_OEM_CLEAR                       VirtualKeyCode = 0xFE
)

type windowsMapper struct {
	codeToName map[VirtualKeyCode]string
}

func init() {
	mapper := &windowsMapper{
		codeToName: make(map[VirtualKeyCode]string),
	}
	mapper.codeToName[VK_LBUTTON] = "VK_LBUTTON"
	mapper.codeToName[VK_RBUTTON] = "VK_RBUTTON"
	mapper.codeToName[VK_CANCEL] = "VK_CANCEL"
	mapper.codeToName[VK_MBUTTON] = "VK_MBUTTON"
	mapper.codeToName[VK_XBUTTON1] = "VK_XBUTTON1"
	mapper.codeToName[VK_XBUTTON2] = "VK_XBUTTON2"
	mapper.codeToName[VK_BACK] = "VK_BACK"
	mapper.codeToName[VK_TAB] = "VK_TAB"
	mapper.codeToName[VK_CLEAR] = "VK_CLEAR"
	mapper.codeToName[VK_RETURN] = "VK_RETURN"
	mapper.codeToName[VK_SHIFT] = "VK_SHIFT"
	mapper.codeToName[VK_CONTROL] = "VK_CONTROL"
	mapper.codeToName[VK_MENU] = "VK_MENU"
	mapper.codeToName[VK_PAUSE] = "VK_PAUSE"
	mapper.codeToName[VK_CAPITAL] = "VK_CAPITAL"
	mapper.codeToName[VK_KANA] = "VK_KANA"
	mapper.codeToName[VK_HANGUL] = "VK_HANGUL"
	mapper.codeToName[VK_IME_ON] = "VK_IME_ON"
	mapper.codeToName[VK_JUNJA] = "VK_JUNJA"
	mapper.codeToName[VK_FINAL] = "VK_FINAL"
	mapper.codeToName[VK_HANJA] = "VK_HANJA"
	mapper.codeToName[VK_KANJI] = "VK_KANJI"
	mapper.codeToName[VK_IME_OFF] = "VK_IME_OFF"
	mapper.codeToName[VK_ESCAPE] = "VK_ESCAPE"
	mapper.codeToName[VK_CONVERT] = "VK_CONVERT"
	mapper.codeToName[VK_NONCONVERT] = "VK_NONCONVERT"
	mapper.codeToName[VK_ACCEPT] = "VK_ACCEPT"
	mapper.codeToName[VK_MODECHANGE] = "VK_MODECHANGE"
	mapper.codeToName[VK_SPACE] = "VK_SPACE"
	mapper.codeToName[VK_PRIOR] = "VK_PRIOR"
	mapper.codeToName[VK_NEXT] = "VK_NEXT"
	mapper.codeToName[VK_END] = "VK_END"
	mapper.codeToName[VK_HOME] = "VK_HOME"
	mapper.codeToName[VK_LEFT] = "VK_LEFT"
	mapper.codeToName[VK_UP] = "VK_UP"
	mapper.codeToName[VK_RIGHT] = "VK_RIGHT"
	mapper.codeToName[VK_DOWN] = "VK_DOWN"
	mapper.codeToName[VK_SELECT] = "VK_SELECT"
	mapper.codeToName[VK_PRINT] = "VK_PRINT"
	mapper.codeToName[VK_EXECUTE] = "VK_EXECUTE"
	mapper.codeToName[VK_SNAPSHOT] = "VK_SNAPSHOT"
	mapper.codeToName[VK_INSERT] = "VK_INSERT"
	mapper.codeToName[VK_DELETE] = "VK_DELETE"
	mapper.codeToName[VK_HELP] = "VK_HELP"
	mapper.codeToName[VK_0] = "VK_0"
	mapper.codeToName[VK_1] = "VK_1"
	mapper.codeToName[VK_2] = "VK_2"
	mapper.codeToName[VK_3] = "VK_3"
	mapper.codeToName[VK_4] = "VK_4"
	mapper.codeToName[VK_5] = "VK_5"
	mapper.codeToName[VK_6] = "VK_6"
	mapper.codeToName[VK_7] = "VK_7"
	mapper.codeToName[VK_8] = "VK_8"
	mapper.codeToName[VK_9] = "VK_9"
	mapper.codeToName[VK_A] = "VK_A"
	mapper.codeToName[VK_B] = "VK_B"
	mapper.codeToName[VK_C] = "VK_C"
	mapper.codeToName[VK_D] = "VK_D"
	mapper.codeToName[VK_E] = "VK_E"
	mapper.codeToName[VK_F] = "VK_F"
	mapper.codeToName[VK_G] = "VK_G"
	mapper.codeToName[VK_H] = "VK_H"
	mapper.codeToName[VK_I] = "VK_I"
	mapper.codeToName[VK_J] = "VK_J"
	mapper.codeToName[VK_K] = "VK_K"
	mapper.codeToName[VK_L] = "VK_L"
	mapper.codeToName[VK_M] = "VK_M"
	mapper.codeToName[VK_N] = "VK_N"
	mapper.codeToName[VK_O] = "VK_O"
	mapper.codeToName[VK_P] = "VK_P"
	mapper.codeToName[VK_Q] = "VK_Q"
	mapper.codeToName[VK_R] = "VK_R"
	mapper.codeToName[VK_S] = "VK_S"
	mapper.codeToName[VK_T] = "VK_T"
	mapper.codeToName[VK_U] = "VK_U"
	mapper.codeToName[VK_V] = "VK_V"
	mapper.codeToName[VK_W] = "VK_W"
	mapper.codeToName[VK_X] = "VK_X"
	mapper.codeToName[VK_Y] = "VK_Y"
	mapper.codeToName[VK_Z] = "VK_Z"
	mapper.codeToName[VK_LWIN] = "VK_LWIN"
	mapper.codeToName[VK_RWIN] = "VK_RWIN"
	mapper.codeToName[VK_APPS] = "VK_APPS"
	mapper.codeToName[VK_SLEEP] = "VK_SLEEP"
	mapper.codeToName[VK_NUMPAD0] = "VK_NUMPAD0"
	mapper.codeToName[VK_NUMPAD1] = "VK_NUMPAD1"
	mapper.codeToName[VK_NUMPAD2] = "VK_NUMPAD2"
	mapper.codeToName[VK_NUMPAD3] = "VK_NUMPAD3"
	mapper.codeToName[VK_NUMPAD4] = "VK_NUMPAD4"
	mapper.codeToName[VK_NUMPAD5] = "VK_NUMPAD5"
	mapper.codeToName[VK_NUMPAD6] = "VK_NUMPAD6"
	mapper.codeToName[VK_NUMPAD7] = "VK_NUMPAD7"
	mapper.codeToName[VK_NUMPAD8] = "VK_NUMPAD8"
	mapper.codeToName[VK_NUMPAD9] = "VK_NUMPAD9"
	mapper.codeToName[VK_MULTIPLY] = "VK_MULTIPLY"
	mapper.codeToName[VK_ADD] = "VK_ADD"
	mapper.codeToName[VK_SEPARATOR] = "VK_SEPARATOR"
	mapper.codeToName[VK_SUBTRACT] = "VK_SUBTRACT"
	mapper.codeToName[VK_DECIMAL] = "VK_DECIMAL"
	mapper.codeToName[VK_DIVIDE] = "VK_DIVIDE"
	mapper.codeToName[VK_F1] = "VK_F1"
	mapper.codeToName[VK_F2] = "VK_F2"
	mapper.codeToName[VK_F3] = "VK_F3"
	mapper.codeToName[VK_F4] = "VK_F4"
	mapper.codeToName[VK_F5] = "VK_F5"
	mapper.codeToName[VK_F6] = "VK_F6"
	mapper.codeToName[VK_F7] = "VK_F7"
	mapper.codeToName[VK_F8] = "VK_F8"
	mapper.codeToName[VK_F9] = "VK_F9"
	mapper.codeToName[VK_F10] = "VK_F10"
	mapper.codeToName[VK_F11] = "VK_F11"
	mapper.codeToName[VK_F12] = "VK_F12"
	mapper.codeToName[VK_F13] = "VK_F13"
	mapper.codeToName[VK_F14] = "VK_F14"
	mapper.codeToName[VK_F15] = "VK_F15"
	mapper.codeToName[VK_F16] = "VK_F16"
	mapper.codeToName[VK_F17] = "VK_F17"
	mapper.codeToName[VK_F18] = "VK_F18"
	mapper.codeToName[VK_F19] = "VK_F19"
	mapper.codeToName[VK_F20] = "VK_F20"
	mapper.codeToName[VK_F21] = "VK_F21"
	mapper.codeToName[VK_F22] = "VK_F22"
	mapper.codeToName[VK_F23] = "VK_F23"
	mapper.codeToName[VK_F24] = "VK_F24"
	mapper.codeToName[VK_NUMLOCK] = "VK_NUMLOCK"
	mapper.codeToName[VK_SCROLL] = "VK_SCROLL"
	mapper.codeToName[VK_LSHIFT] = "VK_LSHIFT"
	mapper.codeToName[VK_RSHIFT] = "VK_RSHIFT"
	mapper.codeToName[VK_LCONTROL] = "VK_LCONTROL"
	mapper.codeToName[VK_RCONTROL] = "VK_RCONTROL"
	mapper.codeToName[VK_LMENU] = "VK_LMENU"
	mapper.codeToName[VK_RMENU] = "VK_RMENU"
	mapper.codeToName[VK_BROWSER_BACK] = "VK_BROWSER_BACK"
	mapper.codeToName[VK_BROWSER_FORWARD] = "VK_BROWSER_FORWARD"
	mapper.codeToName[VK_BROWSER_REFRESH] = "VK_BROWSER_REFRESH"
	mapper.codeToName[VK_BROWSER_STOP] = "VK_BROWSER_STOP"
	mapper.codeToName[VK_BROWSER_SEARCH] = "VK_BROWSER_SEARCH"
	mapper.codeToName[VK_BROWSER_FAVORITES] = "VK_BROWSER_FAVORITES"
	mapper.codeToName[VK_BROWSER_HOME] = "VK_BROWSER_HOME"
	mapper.codeToName[VK_VOLUME_MUTE] = "VK_VOLUME_MUTE"
	mapper.codeToName[VK_VOLUME_DOWN] = "VK_VOLUME_DOWN"
	mapper.codeToName[VK_VOLUME_UP] = "VK_VOLUME_UP"
	mapper.codeToName[VK_MEDIA_NEXT_TRACK] = "VK_MEDIA_NEXT_TRACK"
	mapper.codeToName[VK_MEDIA_PREV_TRACK] = "VK_MEDIA_PREV_TRACK"
	mapper.codeToName[VK_MEDIA_STOP] = "VK_MEDIA_STOP"
	mapper.codeToName[VK_MEDIA_PLAY_PAUSE] = "VK_MEDIA_PLAY_PAUSE"
	mapper.codeToName[VK_LAUNCH_MAIL] = "VK_LAUNCH_MAIL"
	mapper.codeToName[VK_LAUNCH_MEDIA_SELECT] = "VK_LAUNCH_MEDIA_SELECT"
	mapper.codeToName[VK_LAUNCH_APP1] = "VK_LAUNCH_APP1"
	mapper.codeToName[VK_LAUNCH_APP2] = "VK_LAUNCH_APP2"
	mapper.codeToName[VK_OEM_1] = "VK_OEM_1"
	mapper.codeToName[VK_OEM_PLUS] = "VK_OEM_PLUS"
	mapper.codeToName[VK_OEM_COMMA] = "VK_OEM_COMMA"
	mapper.codeToName[VK_OEM_MINUS] = "VK_OEM_MINUS"
	mapper.codeToName[VK_OEM_PERIOD] = "VK_OEM_PERIOD"
	mapper.codeToName[VK_OEM_2] = "VK_OEM_2"
	mapper.codeToName[VK_OEM_3] = "VK_OEM_3"
	mapper.codeToName[VK_GAMEPAD_A] = "VK_GAMEPAD_A"
	mapper.codeToName[VK_GAMEPAD_B] = "VK_GAMEPAD_B"
	mapper.codeToName[VK_GAMEPAD_X] = "VK_GAMEPAD_X"
	mapper.codeToName[VK_GAMEPAD_Y] = "VK_GAMEPAD_Y"
	mapper.codeToName[VK_GAMEPAD_RIGHT_SHOULDER] = "VK_GAMEPAD_RIGHT_SHOULDER"
	mapper.codeToName[VK_GAMEPAD_LEFT_SHOULDER] = "VK_GAMEPAD_LEFT_SHOULDER"
	mapper.codeToName[VK_GAMEPAD_LEFT_TRIGGER] = "VK_GAMEPAD_LEFT_TRIGGER"
	mapper.codeToName[VK_GAMEPAD_RIGHT_TRIGGER] = "VK_GAMEPAD_RIGHT_TRIGGER"
	mapper.codeToName[VK_GAMEPAD_DPAD_UP] = "VK_GAMEPAD_DPAD_UP"
	mapper.codeToName[VK_GAMEPAD_DPAD_DOWN] = "VK_GAMEPAD_DPAD_DOWN"
	mapper.codeToName[VK_GAMEPAD_DPAD_LEFT] = "VK_GAMEPAD_DPAD_LEFT"
	mapper.codeToName[VK_GAMEPAD_DPAD_RIGHT] = "VK_GAMEPAD_DPAD_RIGHT"
	mapper.codeToName[VK_GAMEPAD_MENU] = "VK_GAMEPAD_MENU"
	mapper.codeToName[VK_GAMEPAD_VIEW] = "VK_GAMEPAD_VIEW"
	mapper.codeToName[VK_GAMEPAD_LEFT_THUMBSTICK_BUTTON] = "VK_GAMEPAD_LEFT_THUMBSTICK_BUTTON"
	mapper.codeToName[VK_GAMEPAD_RIGHT_THUMBSTICK_BUTTON] = "VK_GAMEPAD_RIGHT_THUMBSTICK_BUTTON"
	mapper.codeToName[VK_GAMEPAD_LEFT_THUMBSTICK_UP] = "VK_GAMEPAD_LEFT_THUMBSTICK_UP"
	mapper.codeToName[VK_GAMEPAD_LEFT_THUMBSTICK_DOWN] = "VK_GAMEPAD_LEFT_THUMBSTICK_DOWN"
	mapper.codeToName[VK_GAMEPAD_LEFT_THUMBSTICK_RIGHT] = "VK_GAMEPAD_LEFT_THUMBSTICK_RIGHT"
	mapper.codeToName[VK_GAMEPAD_LEFT_THUMBSTICK_LEFT] = "VK_GAMEPAD_LEFT_THUMBSTICK_LEFT"
	mapper.codeToName[VK_GAMEPAD_RIGHT_THUMBSTICK_UP] = "VK_GAMEPAD_RIGHT_THUMBSTICK_UP"
	mapper.codeToName[VK_GAMEPAD_RIGHT_THUMBSTICK_DOWN] = "VK_GAMEPAD_RIGHT_THUMBSTICK_DOWN"
	mapper.codeToName[VK_GAMEPAD_RIGHT_THUMBSTICK_RIGHT] = "VK_GAMEPAD_RIGHT_THUMBSTICK_RIGHT"
	mapper.codeToName[VK_GAMEPAD_RIGHT_THUMBSTICK_LEFT] = "VK_GAMEPAD_RIGHT_THUMBSTICK_LEFT"
	mapper.codeToName[VK_OEM_4] = "VK_OEM_4"
	mapper.codeToName[VK_OEM_5] = "VK_OEM_5"
	mapper.codeToName[VK_OEM_6] = "VK_OEM_6"
	mapper.codeToName[VK_OEM_7] = "VK_OEM_7"
	mapper.codeToName[VK_OEM_8] = "VK_OEM_8"
	mapper.codeToName[VK_OEM_102] = "VK_OEM_102"
	mapper.codeToName[VK_PROCESSKEY] = "VK_PROCESSKEY"
	mapper.codeToName[VK_PACKET] = "VK_PACKET"
	mapper.codeToName[VK_ATTN] = "VK_ATTN"
	mapper.codeToName[VK_CRSEL] = "VK_CRSEL"
	mapper.codeToName[VK_EXSEL] = "VK_EXSEL"
	mapper.codeToName[VK_EREOF] = "VK_EREOF"
	mapper.codeToName[VK_PLAY] = "VK_PLAY"
	mapper.codeToName[VK_ZOOM] = "VK_ZOOM"
	mapper.codeToName[VK_NONAME] = "VK_NONAME"
	mapper.codeToName[VK_PA1] = "VK_PA1"
	mapper.codeToName[VK_OEM_CLEAR] = "VK_OEM_CLEAR"
	globalMapper = mapper
}

func (m *windowsMapper) Normalize(code any) string {
	// 支持直接传入 VirtualKeyCode 类型
	if c, ok := code.(VirtualKeyCode); ok {
		if name, ok := m.codeToName[c]; ok {
			return name
		}
	}
	// 兼容直接传入 uint16
	if c, ok := code.(uint16); ok {
		if name, ok := m.codeToName[VirtualKeyCode(c)]; ok {
			return name
		}
	}
	return "Unknown"
}

func GetKeyLayout(l LayoutType) Layout {
	return Layout{}
}
