// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Service represents the dock service
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * GetBadge returns the badge label on the application icon.
 * @returns {$CancellablePromise<string | null>}
 */
export function GetBadge() {
    return $Call.ByID(1150236961);
}

/**
 * HideAppIcon hides the app icon in the dock/taskbar.
 * @returns {$CancellablePromise<void>}
 */
export function HideAppIcon() {
    return $Call.ByID(3413658144);
}

/**
 * RemoveBadge removes the badge label from the application icon.
 * @returns {$CancellablePromise<void>}
 */
export function RemoveBadge() {
    return $Call.ByID(2752757297);
}

/**
 * SetBadge sets the badge label on the application icon.
 * @param {string} label
 * @returns {$CancellablePromise<void>}
 */
export function SetBadge(label) {
    return $Call.ByID(1717705661, label);
}

/**
 * SetCustomBadge sets the badge label on the application icon with custom options.
 * @param {string} label
 * @param {$models.BadgeOptions} options
 * @returns {$CancellablePromise<void>}
 */
export function SetCustomBadge(label, options) {
    return $Call.ByID(2730169760, label, options);
}

/**
 * ShowAppIcon shows the app icon in the dock/taskbar.
 * @returns {$CancellablePromise<void>}
 */
export function ShowAppIcon() {
    return $Call.ByID(3409697379);
}
