// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import * as DockService from "./dockservice.js";
export {
    DockService
};

export {
    BadgeOptions
} from "./models.js";
