// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class Key {
    /**
     * Creates a new Key instance.
     * @param {Partial<Key>} [$$source = {}] - The source object to create the Key.
     */
    constructor($$source = {}) {
        if (!("Code" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Code"] = "";
        }
        if (!("Label" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Label"] = "";
        }
        if (!("W" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["W"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Key instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Key}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Key(/** @type {Partial<Key>} */($$parsedSource));
    }
}

/**
 * @typedef {Key[][]} Layout
 */

/**
 * @readonly
 * @enum {string}
 */
export const LayoutType = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    LayoutANSI: "ANSI",
};
